# Generated by Django 3.2.7 on 2021-09-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celeryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodels',
            name='make_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
